services:
  - type: web
    name: n8n
    runtime: docker
    dockerfilePath: ./docker/images/n8n/Dockerfile.render
    dockerContext: .
    plan: free
    nodeBuild:
      nodeVersion: 20.15.0
    scaling:
      minInstances: 1
      maxInstances: 1
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        generateValue: true
      - key: N8N_HOST
        fromService:
          type: web
          name: n8n
          envVarKey: RENDER_EXTERNAL_HOSTNAME
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_PORT
        value: 5678
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: DB_TYPE
        value: sqlite
      - key: N8N_LOG_LEVEL
        value: info
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: n8n
          envVarKey: RENDER_EXTERNAL_URL
      - key: TZ
        value: Asia/Tokyo
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
      - key: N8N_API_ALLOW_ORIGIN
        value: "*"
      - key: NODE_VERSION
        value: "20.15.0"
      - key: NODE_VERSION_CHECK
        value: "false"
    disk:
      name: n8n-data
      mountPath: /data
      sizeGB: 1
    healthCheckPath: /healthz 